---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: ansible-lint
platforms:
  - name: instance-1
    image: molecule_local/centos:7
    command: sleep infinity
    dockerfile: Dockerfile
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
